### ISSUE TITLE
Upgrading from 9.6 to 10 : invalid PG_VERSION path

### ISSUE THREAD

**Issue by LudovicSoltysOAB** [tianon/docker-postgres-upgrade#12]
Hello,

I'm a beginner to docker and to postgres as well. I've been asked to upgrade postgres from 9.6 to 10. So thank you very much for this image !

 In my case, all the data is in 9.6/main, instead of 9.6/data. When i try to upgrade postgres, i get the following message :
`$ sudo docker run --rm -v /etc/postgresql/9.6/main:/var/lib/postgresql/9.6/main -v /etc/postgresql/10/main:/var/lib/postgresql/10/main tianon/postgres-upgrade:9.6-to-10 --link

...
Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/10/data -l logfile start

could not open version file: /var/lib/postgresql/9.6/data/PG_VERSION
Failure, exiting`

Can you help me ?

Best regards,
Ludovic

**Comment by tianon** [comment]
Using `--link` will _not_ work with two separate `-v` mounts (re-read through https://github.com/tianon/docker-postgres-upgrade#readme, which explains this).

Additionally, if your data is not under `/data`, you either need to rename your folder to get it there, or you need to follow the alternate instructions (so that it's `/data` inside the container), which will be slower than doing the rename, using a single `-v`, and using `--link`.

**Comment by tianon** [comment]
In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
