### ISSUE TITLE
PostgreSQL 16

### ISSUE THREAD

**Issue by ThaDaVos** [tianon/docker-postgres-upgrade#75]
Postgress released v16 last thursday - when can we expect an updated image?

https://www.postgresql.org/docs/release/16.0/

**Comment by tianon** [comment]
Expect might be an unfortunate word choice; I wouldn't recommend expecting
anything from this image. 😅

It's very much a best effort PoC that I haven't really spent much time
maintaining since I originally wrote it many years ago.

That being said, I'll probably add 16 eventually, there's just not really
any guarantee of when I'll get to it (especially as I'm currently on an
extended leave).

**Comment by SAMWEL2018** [comment]
@tianon This is much to wait, I rushed to your repo hoping you have already updated. my request is from 11 to 16.

**Comment by realies** [comment]
@ThaDaVos check #78.
